services:
  portainer:
    image: portainer/portainer-ce:lts
    ports:
      # HTTP
      - target: 9000
        published: 9000
        mode: host
      # HTTPS
      - target: 9443
        published: 9443
        mode: host
    volumes:
      - type: npipe
        source: '\\.\pipe\docker_engine'
        target: '\\.\pipe\docker_engine'
      - 'data:C:\data'
    networks:
      - nat

volumes:
  data:

networks:
  nat:
    external: true